use std::time::Duration;

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Chat roles. `/api/chat` is role-separated by construction, unlike the
/// `/api/generate` + concatenated string every current call in the Godot
/// build uses (B-2): an instruction-tuned model gets its own chat template
/// applied instead of receiving instructions in a format it was never tuned
/// on.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    System,
    User,
    Assistant,
    Tool,
}

/// One role-separated message. `tool_calls` is populated on an assistant
/// message that invoked a tool; `tool_call_id` + `name` identify which call a
/// `Tool` role message is answering.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    pub role: Role,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ChatMessage {
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: Role::System,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: None,
            name: None,
        }
    }

    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: Role::User,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: None,
            name: None,
        }
    }

    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: Role::Assistant,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: None,
            name: None,
        }
    }

    pub fn tool_result(tool_call_id: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            role: Role::Tool,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: Some(tool_call_id.into()),
            name: None,
        }
    }
}

/// A model-issued call to one of the tools offered in [`ChatRequest::tools`].
/// Arguments arrive as a JSON value; a caller decodes them into a typed
/// `ToolArgs` struct (see `inference::tools`) rather than parsing prose,
/// which is the whole point of native tool calling (§2.6).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    #[serde(default)]
    pub id: Option<String>,
    pub name: String,
    #[serde(default)]
    pub arguments: serde_json::Value,
}

/// A tool definition sent to the backend. `parameters` is a JSON Schema
/// generated by `schemars` from the same Rust type that decodes the
/// resulting `ToolCall::arguments`, so drift between what a tool accepts and
/// what the caller parses is not representable.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolDefinition {
    pub name: String,
    pub description: String,
    pub parameters: serde_json::Value,
}

/// Requests schema-constrained decoding. `schema` is a JSON Schema generated
/// by `schemars::schema_for!` from the type the caller will deserialize the
/// response into. This is the direct replacement for the legacy
/// `format: "json"` flag (B-3): that flag guarantees syntactic JSON but
/// nothing about fields, types, or enum values, which is why `JsonRepair.gd`
/// existed. A schema sent here constrains sampling itself.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResponseFormat {
    pub schema: serde_json::Value,
}

impl ResponseFormat {
    /// Build a response format from a type's own `JsonSchema` derive. The
    /// schema sent to the decoder and the type that later deserializes the
    /// response are the same type: they cannot drift.
    pub fn for_type<T: JsonSchema>() -> Self {
        let root = super::schema::root_schema::<T>();
        Self {
            schema: serde_json::to_value(root).expect("schemars root schema is always valid JSON"),
        }
    }
}

/// How long the backend should keep a model resident after this request.
/// The Godot build sends `keep_alive: -1` on every request for both models
/// (B-6), which pins both permanently in VRAM — hostile on an 8GB consumer
/// GPU shared with image generation. The default here is a bounded duration.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum KeepAlive {
    /// Unload as soon as the request completes.
    Immediate,
    /// Keep resident for this long after the last request.
    For(Duration),
    /// Keep resident indefinitely. Opt in explicitly; this is the old
    /// default and the thing B-6 flags as hostile.
    Forever,
}

impl Default for KeepAlive {
    fn default() -> Self {
        // Long enough to survive back-to-back turns in one scene without
        // reload latency; short enough to free VRAM between sessions.
        KeepAlive::For(Duration::from_secs(5 * 60))
    }
}

impl Serialize for KeepAlive {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        match self {
            KeepAlive::Immediate => serializer.serialize_str("0s"),
            KeepAlive::Forever => serializer.serialize_i64(-1),
            KeepAlive::For(d) => serializer.serialize_str(&format!("{}s", d.as_secs())),
        }
    }
}

#[derive(Debug, Clone, Default)]
pub struct SamplingOptions {
    pub temperature: f32,
    pub top_p: f32,
}

impl SamplingOptions {
    pub fn new(temperature: f32, top_p: f32) -> Self {
        Self { temperature, top_p }
    }
}

/// A single chat completion request. Message order matters for KV-cache
/// reuse: see `crate::prompt::ordering` for the cache-stable assembly this
/// is meant to receive (§2.7). Nothing in this type hardcodes a context
/// length; the caller derives `messages` and any truncation from
/// `InferenceBackend::context_length()`.
#[derive(Debug, Clone)]
pub struct ChatRequest {
    pub messages: Vec<ChatMessage>,
    pub tools: Vec<ToolDefinition>,
    pub response_format: Option<ResponseFormat>,
    pub sampling: SamplingOptions,
    pub keep_alive: KeepAlive,
}

impl ChatRequest {
    pub fn new(messages: Vec<ChatMessage>) -> Self {
        Self {
            messages,
            tools: Vec::new(),
            response_format: None,
            sampling: SamplingOptions::new(0.7, 0.9),
            keep_alive: KeepAlive::default(),
        }
    }

    pub fn with_tools(mut self, tools: Vec<ToolDefinition>) -> Self {
        self.tools = tools;
        self
    }

    pub fn with_response_format(mut self, format: ResponseFormat) -> Self {
        self.response_format = Some(format);
        self
    }

    pub fn with_keep_alive(mut self, keep_alive: KeepAlive) -> Self {
        self.keep_alive = keep_alive;
        self
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum DoneReason {
    Stop,
    ToolCalls,
    Length,
    Other,
}

#[derive(Debug, Clone)]
pub struct ChatResponse {
    pub message: ChatMessage,
    pub done_reason: DoneReason,
    pub prompt_tokens: usize,
    pub completion_tokens: usize,
}

impl ChatResponse {
    /// Deserialize the message content into a schema-constrained response
    /// type. Call this only when the request carried a matching
    /// `ResponseFormat` for `T`; the backend has already constrained
    /// sampling to that schema; this is the parse half of the same
    /// contract, so mismatch is a backend bug rather than an expected case
    /// to repair (`JsonRepair.gd` is not ported — see §2.4).
    pub fn parse<T: for<'de> Deserialize<'de>>(&self) -> Result<T, super::error::InferenceError> {
        let content = self.message.content.as_deref().unwrap_or_default();
        serde_json::from_str(content).map_err(Into::into)
    }
}

/// One incremental piece of a streamed chat response.
#[derive(Debug, Clone, Default)]
pub struct ChatDelta {
    pub content: Option<String>,
    pub tool_calls: Option<Vec<ToolCall>>,
    pub done: bool,
}

#[derive(Debug, Clone, Copy, Default)]
pub struct Capabilities {
    pub tools: bool,
    pub structured_output: bool,
    pub vision: bool,
    pub streaming: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub enum HealthStatus {
    Available,
    /// The endpoint answered but the configured model is not present there.
    ModelNotInstalled,
    /// The endpoint itself could not be reached.
    Unreachable {
        detail: String,
    },
}

/// The direct fix for B-15. In the Godot build, `LLMClient.send_prompt()`
/// treated an HTTP 404 for a missing model no differently from a normal
/// non-streaming failure: `request_failed` fired, but nothing forced a
/// caller to check for it, so "RAPTOR summaries generated successfully" could
/// print over an empty result. `health()` returns this type and every
/// backend implementation must answer it truthfully before any caller may
/// print a success message.
#[derive(Debug, Clone, PartialEq)]
pub struct ModelHealth {
    pub model: String,
    pub status: HealthStatus,
    pub context_length: Option<usize>,
}

impl ModelHealth {
    pub fn is_available(&self) -> bool {
        self.status == HealthStatus::Available
    }
}
